### ISSUE TITLE
Error: Invalid path ''

### ISSUE THREAD

**Issue by amccloud** [mjohnston/react-native-webpack-server#11]
After the packager starts I get this error

```
React packager ready.

|
Error: Invalid path ''
    at pathToArray (/Users/amccloud/.Labs/Nom/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:23:38)
    at MemoryFileSystem.mkdirpSync (/Users/amccloud/.Labs/Nom/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:107:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/amccloud/.Labs/Nom/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:187:34)
    at Tapable.<anonymous> (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compiler.js:219:25)
    at Tapable.applyPluginsAsync (/Users/amccloud/.Labs/Nom/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.Compiler.emitAssets (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compiler.js:216:7)
    at Watching.<anonymous> (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compiler.js:45:18)
    at /Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compiler.js:392:12
    at Tapable.next (/Users/amccloud/.Labs/Nom/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Tapable.<anonymous> (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Tapable.applyPluginsAsync (/Users/amccloud/.Labs/Nom/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compiler.js:389:9)
    at Tapable.<anonymous> (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compilation.js:549:13)
    at Tapable.applyPluginsAsync (/Users/amccloud/.Labs/Nom/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.<anonymous> (/Users/amccloud/.Labs/Nom/node_modules/webpack/lib/Compilation.js:544:10)
    at Tapable.applyPluginsAsync (/Users/amccloud/.Labs/Nom/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
```

**Comment by amccloud** [comment]
Looks like it's an upstream issue https://github.com/webpack/webpack-dev-server/issues/88
