### ISSUE TITLE
Error: File /Users/mtford/Playground/CodenameBig/node_modules/react-native-webpack-server/node_modules/connect/node_modules/finalhandler/node_modules/on-finished/node_modules/ee-first/index.js not found in any of the roots

### ISSUE THREAD

**Issue by mtford90** [mjohnston/react-native-webpack-server#46]
Hi,

Having issues getting this up and running - I copied from the babel example.

I get a red screen in the app and the following error in the terminal when running in the simulator:

```
Error: File /Users/mtford/Playground/CodenameBig/node_modules/react-native-webpack-server/node_modules/connect/node_modules/finalhandler/node_modules/on-finished/node_modules/ee-first/index.js not found in any of the roots
    at Fastfs._getAndAssertRoot (/Users/mtford/Playground/CodenameBig/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:137:13)
    at Fastfs._add (/Users/mtford/Playground/CodenameBig/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:152:10)
    at /Users/mtford/Playground/CodenameBig/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:38:18
    at Array.forEach (native)
    at /Users/mtford/Playground/CodenameBig/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:31:13
    at tryCallOne (/Users/mtford/Playground/CodenameBig/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/mtford/Playground/CodenameBig/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/mtford/Playground/CodenameBig/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:442:13)
{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}
```

The project is available at https://github.com/mtford90/codename-big if you wanna take a look at the setup. 

Any help would be much appreciated!

**Comment by elliottsj** [comment]
Can you try out version `0.3.0` of react-native-webpack-server?
