### ISSUE TITLE
Change to make it work in RN 0.9.0

### ISSUE THREAD

**Issue by leoasis** [mjohnston/react-native-webpack-server#50]
I was running into an error when trying the latest version with RN 0.9.0 saying that "React" is not defined, and I was able to track the error down to this file/line: https://github.com/mjohnston/react-native-webpack-server/blob/4aa6f63accd7501b22bb83fcb6043b297707e567/lib/getReactNativeExternals.js#L41

It seems that at least in RN 0.9.0, the React variable is no longer defined in the global scope.

By changing it to the following, everything started working without errors, and hot reload was working again perfectly:

``` js
externals['react-native'] = "require('react-native/Libraries/react-native/react-native.js')";
```

I'm not sure this is the correct fix, but posting it here if anyone more familiarized with the internals of the RN packager + the internals of RN webpack server can work the correct solution out from this.

If this happens to be the correct solution, I'm happy to send this as a PR though.

**Comment by elliottsj** [comment]
I've been using my changes from #48 and haven't had any issues so far with 0.9.0. I've removed the 

``` js
externals['react-native'] = 'React';
```

line from getReactNativeExternals.js since `require('react-native')` seems to work as-is.

**Comment by leoasis** [comment]
@elliottsj  I've just tried your branch (which seems to be the right path), but I'm running into this error:

``` sh
Server listening at http://localhost:8083
Unable to resolve module react-timer-mixin from .../node_modules/react-native/Libraries/CustomComponents/ListView/ListView.js
Unable to resolve module react-timer-mixin from .../node_modules/react-native/Libraries/CustomComponents/Navigator/Navigator.js
Unable to resolve module immutable from .../node_modules/react-native/Libraries/CustomComponents/Navigator/NavigatorBreadcrumbNavigationBar.js
Unable to resolve module immutable from .../node_modules/react-native/Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js
Unable to resolve module react-timer-mixin from .../node_modules/react-native/Libraries/Components/TextInput/TextInput.js
Unable to resolve module react-timer-mixin from .../node_modules/react-native/Libraries/Components/Touchable/TouchableWithoutFeedback.js
Unable to resolve module react-timer-mixin from .../node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js
Unable to resolve module react-timer-mixin from .../node_modules/react-native/Libraries/Components/Touchable/TouchableOpacity.js
Webpack dev server listening at  http://localhost:8082
Hash: bfc8ee13369c812c1bb1
Version: webpack 1.11.0
Time: 4831ms
       Asset    Size  Chunks       Chunk Names
index.ios.js  5.4 MB       0       index.ios
chunk    {0} index.ios.js (index.ios) 2.01 MB [rendered]

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module build failed: SyntaxError: .../node_modules/react-native/Libraries/react-native/react-native.js: Line 20: Did you mean "react"?
  18 | //   var ReactNative = {...require('React'), /* additions */}
  19 | //
> 20 | var ReactNative = Object.assign(Object.create(require('React')), {
     |                                                       ^
  21 |   // Components
  22 |   ActivityIndicatorIOS: require('ActivityIndicatorIOS'),
  23 |   DatePickerIOS: require('DatePickerIOS'),
    at File.errorWithNode (.../node_modules/babel-core/lib/transformation/file/index.js:488:13)
    at check (.../node_modules/babel-core/lib/transformation/transformers/validation/react.js:24:18)
    at NodePath.CallExpression (.../node_modules/babel-core/lib/transformation/transformers/validation/react.js:41:7)
    at NodePath.call (.../node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (.../node_modules/babel-core/lib/traversal/path/context.js:89:8)
    at TraversalContext.visitMultiple (.../node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (.../node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (.../node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (.../node_modules/babel-core/lib/traversal/path/context.js:106:26)
    at TraversalContext.visitMultiple (.../node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (.../node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (.../node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (.../node_modules/babel-core/lib/traversal/path/context.js:106:26)
    at TraversalContext.visitSingle (.../node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (.../node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (.../node_modules/babel-core/lib/traversal/index.js:76:17)
 @ ./React/index.js 10:12-35
webpack: bundle is now VALID.
```

any idea what I may be missing?

**Comment by elliottsj** [comment]
Hmm, not quite sure. I'll try to create an example project this evening

**Comment by elliottsj** [comment]
@leoasis Here's an example project using changes from #48: https://github.com/elliottsj/react-native-webpack-server-example

**Comment by leoasis** [comment]
@elliottsj that example is not configured to use webpack in hot mode (to be able to use react-hot-loader), perhaps that's when you get the error?

**Comment by elliottsj** [comment]
@leoasis Yeah, perhaps. I'll update my example tonight

**Comment by leoasis** [comment]
Thanks @elliottsj! Really looking forward for the proper fix for this, and you seem to be near it

**Comment by elliottsj** [comment]
@leoasis I've added the hot loading configuration: https://github.com/elliottsj/react-native-webpack-server-example/commit/c31216fbc1d709d602364245903d4b5ad69f3364

Seems to work on my end; let me know if it works for you

**Comment by leoasis** [comment]
When I try to run your example in hot mode (`npm run hot`) I get the following errors:

``` sh
Server listening at http://localhost:8080
Webpack dev server listening at  http://localhost:8082
Hash: 35612fd5f5baeabab344
Version: webpack 1.12.0
Time: 910ms
       Asset    Size  Chunks             Chunk Names
index.ios.js  304 kB       0  [emitted]  main
chunk    {0} index.ios.js (main) 197 kB [rendered]

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /Users/lenny/dev/others/react-native-webpack-server-example/src
 @ ./src/index.js 1:382-413

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react' in /Users/lenny/dev/others/react-native-webpack-server-example/src
 @ ./src/index.js 1:423-439 19:378-394

ERROR in ./src/Example.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /Users/lenny/dev/others/react-native-webpack-server-example/src
 @ ./src/Example.js 1:382-413

ERROR in ./src/Example.js
Module not found: Error: Cannot resolve module 'react' in /Users/lenny/dev/others/react-native-webpack-server-example/src
 @ ./src/Example.js 1:423-439 59:378-394
webpack: bundle is now VALID.
```

I tried it with both node 0.12.4 and iojs 3.0.0, and got the same error.

**Comment by elliottsj** [comment]
https://github.com/elliottsj/react-native-webpack-server-example/issues/1#issuecomment-135143345

**Comment by elliottsj** [comment]
@leoasis See https://github.com/elliottsj/react-native-webpack-server-example/issues/1#issuecomment-135232617, I think hot loading will work now.

**Comment by elliottsj** [comment]
@leoasis Were you able to get hot loading to work in your project? Closing for now
